site_name: Worktile企业版帮助中心
site_url: https://pro.worktile.com/help
repo_url: https://github.com/lesschat/guide
repo_name: GitHub
site_favicon: favicon.ico
site_description: Worktile企业版帮助中心
site_author: yctech
copyright:  'Copyright&copy;2016 Worktile 企业版'
#google_analytics: ['UA-36723568-3', 'mkdocs.org']
include_next_prev: false
pages:
- [index.md, '快速开始']
- [message/index.md, '聊天']
- [task/index.md, '任务']
- [calendar/index.md, '日历']
- [drive/index.md, '网盘']
- [report/index.md, '简报']
- [phone/index.md, 电话]
- [contacts/index.md, 通讯录]

- [admin/index.md, '管理员手册']
- [admin/dashboard.md, '管理员手册 ', '控制台']
- [admin/members.md, '管理员手册 ', '成员管理']
- [admin/apps.md, '管理员手册 ', '应用管理']
- [admin/services.md, '管理员手册 ', '服务管理']
- [admin/setting.md, '管理员手册 ', '企业设置']
- [admin/billing.md, '管理员手册 ', '账单管理']
- [admin/security.md, '管理员手册 ', '安全管理']
- [admin/stat.md, '管理员手册 ', '数据统计']


#- [support.md, '联系客服']

#theme: readthedocs
theme_dir: 'theme/default'
#theme_dir: 'theme/mkdocs'
docs_dir: 'docs'
site_dir: 'site'